adds login.jsx
d1360cub/mental-health-front pull request #15
Opened 2022-03-11 22:32 UTC by d1360cub

Adds component login, includes styles and image

2022-03-12 15:28 UTC, mhbuiles requested changes

2022-03-12 15:28 UTC, mhbuiles commented on src/Components/Login.css
> +/*body {
No dejemos líneas de código comentadas.

2022-03-12 15:28 UTC, mhbuiles commented on src/Components/Login.jsx
> +function Login(props) {
Para qué recibimos props en este componente si luego no los usamos en ningún lugar?

2022-03-12 20:07 UTC, d1360cub reviewed
changes requested done

2022-03-14 18:41 UTC, mhbuiles approved these changes

2022-03-14 18:43 UTC, endyleyms approved these changes

2022-03-15 14:27 UTC, closed without merging