Page doc pat
d1360cub/mental-health-front pull request #23
Opened 2022-03-16 13:30 UTC by AlexSuarezRodriguez

2022-03-17 13:15 UTC, mhbuiles requested changes

2022-03-17 13:15 UTC, mhbuiles commented on src/App.js
> + console.log(datadoctor)
No console.log

2022-03-17 13:15 UTC, mhbuiles commented on src/Components/CardViewer.jsx
> +            return <Enlace path={element.path} url={element.url}/> ;
En una lista de React debemos agregar el prop especial "key".

2022-03-17 13:15 UTC, mhbuiles commented on src/Pages/ViewerDoctor.jsx
> +              <CardViewer information={element} links={links}/>
Hace falta el prop "key".

2022-03-17 19:47 UTC, mhbuiles requested changes

2022-03-17 19:47 UTC, mhbuiles commented on src/Components/Enlace.jsx
> +    <a className="btn-appointment" href={url} key={key} > {path} </a>
Aquí no es necesario el prop "key" porque esto no es una lista, es un solo enlace.

2022-03-18 16:36 UTC, mhbuiles submitted a review, later dismissed

2022-03-18 16:36 UTC, mhbuiles commented on src/Pages/viewerDoctor/ViewerDoctor.jsx
> +            return  <Welcome information={element} key={index}/>
Investiguen por qué no es una buena idea usar el índex como key.

2022-03-18 16:36 UTC, mhbuiles commented on src/Pages/viewerPatient/ViewerPatient.jsx
> +  const listPerson=async()=>{
Esto no debería estar dentro de un useEffect??

2022-03-18 16:39 UTC, d1360cub commented on src/Pages/viewerDoctor/ViewerDoctor.jsx
> +            return  <Welcome information={element} key={index}/>
podría usar el id como key?

2022-03-18 16:41 UTC, mhbuiles commented on src/Pages/viewerDoctor/ViewerDoctor.jsx
> +            return  <Welcome information={element} key={index}/>
Sí

2022-03-18 18:08 UTC, AlexSuarezRodriguez commented on src/Pages/viewerPatient/ViewerPatient.jsx
> +  const listPerson=async()=>{
mateo consulta que es como una pregunta , cuando uno construye una funcion dentro de un useEffect esta haciendo que el dato que retorne no se accedido por otros fuera de ese useEffect haciendola inalcansable ,al dejarla por fuera ya puede ser accedida o manipular el dato que retorna ?

2022-03-18 21:40 UTC, endyleyms approved these changes

2022-03-18 21:40 UTC, d1360cub approved these changes
a la ciega

2022-03-18 21:42 UTC, popehiflo approved these changes
Go!

2022-03-18 21:46 UTC, merged