Feat/doc register
d1360cub/mental-health-front pull request #40
Opened 2022-03-23 15:47 UTC by d1360cub

Adds show password to login, adds modal to doctor register, adds doctor register

2022-03-23 15:52 UTC, mherreraatleantech requested changes

2022-03-23 15:52 UTC, mherreraatleantech commented on db.json
> +      "id": 7
Por qué este objeto solo tiene el id?

2022-03-23 15:52 UTC, mherreraatleantech commented on src/Pages/DoctorSignup/DoctorSignup.jsx
> +    console.log(form);
No console.log

2022-03-23 23:35 UTC, d1360cub commented on db.json
> +      "id": 7
deleted

2022-03-23 23:35 UTC, d1360cub reviewed
modified

2022-03-23 23:35 UTC, d1360cub commented on src/Pages/DoctorSignup/DoctorSignup.jsx
> +    console.log(form);
deleted

2022-03-24 20:54 UTC, mherreraatleantech approved these changes

2022-03-24 20:59 UTC, mhbuiles approved these changes

2022-03-24 22:59 UTC, merged